image: docker.io/gumjoe/wacc-ci-scala:slim

stages:         
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - echo "Building..."
    - scala-cli .
    - echo "Build complete."

unit-test-job:  
  stage: test   
  script:
    - echo "Running unit tests..."
    - scala-cli test .
    - echo "Tests complete."

lint-test-job:
  stage: test
  script: 
    - echo "Linting..."
    - scalafix .
    - echo "Linting complete."

#Dummy commit to test pipeline
