image: docker.io/gumjoe/wacc-ci-scala:slim

stages:         
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - echo "Building..."
    - make
    - echo "Build complete."

unit-test-job:  
  stage: test   
  script:
    - echo "Running unit tests..."
    - scala-cli test .
    - echo "Unit tests complete."

integration-test-job:  
  stage: test   
  script:
    - echo "Running integration tests..."
    - ./test.sh
    - echo "Integation tests complete."

lint-test-job:
  stage: test
  script: 
    - echo "Linting..."
    - scala-cli compile . --test --server=false
    - scalafix --check src --scalac-options "-Xlint:unused" --auto-classpath --stdout
    - echo "Linting complete."
